# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GEBlockChain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GEBlockChain

  pod ‘Hue', '~> 5.0.0'

  pod 'Kingfisher', '5.10.1'

  pod 'IQKeyboardManagerSwift'

  pod 'JXPopupView', '~> 0.0.5'

  pod 'SnapKit', '~> 5.0.1'

  pod 'PKHUD'

  pod 'ReactiveSwift'

  pod 'ReactiveCocoa'

  pod 'Alamofire', '~> 5.2'
  
  pod 'Moya/ReactiveSwift', '~> 14.0'
  
  pod 'SJRouter'
  
  pod 'Charts'

  pod 'MJRefresh'
  
  pod 'Parchment', '~> 2.4.0'
  
  #滚动页
  pod 'LTScrollView'
  
  #tabbar样式
  pod 'ESTabBarController-swift', '~> 2.6.2'
    
  target 'GEBlockChainTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
